"""Initial migration.

Revision ID: 22d09218a13a
Revises: 
Create Date: 2020-04-11 21:11:21.894716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d09218a13a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('blogpost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogpost',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('subtitle', sa.VARCHAR(length=50), nullable=True),
    sa.Column('author', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date_posted', sa.DATETIME(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('subtitle', sa.VARCHAR(length=50), nullable=True),
    sa.Column('author', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date_posted', sa.DATETIME(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('score', sa.VARCHAR(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
