"""empty message

Revision ID: 4328faabfd9d
Revises: 7ce1363d11e0
Create Date: 2020-04-11 23:42:39.842628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4328faabfd9d'
down_revision = '7ce1363d11e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('art_filename', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'art_filename')
    # ### end Alembic commands ###
