"""empty message

Revision ID: 8e2bd7a4b5dd
Revises: cf6ab2e1294c
Create Date: 2020-05-01 20:15:28.363365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2bd7a4b5dd'
down_revision = 'cf6ab2e1294c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('is_published', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('is_published', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'is_published')
    op.drop_column('blogpost', 'is_published')
    # ### end Alembic commands ###
