"""empty message

Revision ID: ba2084a033ed
Revises: c24e5f51fa2f
Create Date: 2020-05-06 15:06:14.463467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2084a033ed'
down_revision = 'c24e5f51fa2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('review', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'updated_at')
    op.drop_column('blogpost', 'updated_at')
    # ### end Alembic commands ###
